CONFIG = {
  "n_way": 5,
  "k_shot": 5,
  "n_query": 2,
  "lr": 1e-4,
  "weight_decay": 1e-4,
  "iters": 10,
  "epochs": 100,
  "batch_size": 16,
  "in_channels": 3,
  "hidden_channels": 6,
  "out_channels": 3,
  "kernel_size": 3,
  "bias": False,
  "scheduler": True,
  "clip_grad": False,
} # CONFIG