CONFIG = {
  "n_way": 5,
  "k_shot": 5,
  "n_query": 2,
  "lr": 1e-5,
  "weight_decay": 1e-4,
  "iters": 8,
  "epochs": 50,
  "batch_size": 16,
  "in_channels": 3,
  "hidden_channels": 12,
  "out_channels": 3,
  "kernel_size": 3,
  "clip_grad": False,
} # CONFIG